### ISSUE TITLE
[BUG][FLINK-24733] Data loss in pulsar source when using shared mode

### ISSUE THREAD

**Issue by syhily** [streamnative/flink#16]
The PR is completed by a community people: https://github.com/apache/flink/pull/17643/files

**Comment by syhily** [comment]
@nlu90 The reason why the data loss has been confirmed. A [quick fix](https://gist.github.com/syhily/fbf47b581257f94869c59660002bbfa1) has been submitted. I'm waiting for the response from the reporter.

**Comment by syhily** [comment]
The reporter is named 王志升 from sina.

**Comment by nlu90** [comment]
Cool. I added one comment regarding one place.

**Comment by syhily** [comment]
@imaffe Can we add tests for this issue.

**Comment by syhily** [comment]
The test from the reporter is [here](https://gist.github.com/wsz94/bbbcbf84e5a8ec7098ecc4fa1684f172). But I don't think this test is acceptable. I'll help him finish the test.

**Comment by imaffe** [comment]
> The test from the reporter is [here](https://gist.github.com/wsz94/bbbcbf84e5a8ec7098ecc4fa1684f172). But I don't think this test is acceptable. I'll help him finish the test.

After the PulsarOrderedReaderTest is merged, I think we can add a test there as well.

**Comment by syhily** [comment]
@imaffe The fix has been finished with test on branch `hotfix/data-lose-when-timeout`

**Comment by syhily** [comment]
Closed for the related PR is ready. We are just waiting for the flink ci pass and the final confirmation from the flink community.
