### ISSUE TITLE
[SQL Connector] error: Can not create transaction system topic

### ISSUE THREAD

**Issue by futeng** [streamnative/flink#160]
In the shared and key shared modes, the first execution is OK, and there will be errors when redoing (whether it is the same consumer or a new consumer).

```
Can not create transaction system topic persistent://data-warehouse/ogg/EBS.INV.MTL_SYSTEM_ITEMS_TL-partition-0-flink-test__transaction_pending_ack
```

Version
- flink-sql-connector-pulsar: 1.15.0.1 
- pulsar 2.9.2.17

**Comment by syhily** [comment]
This issue could happen on the Pulsar side. Maybe you should ask congbo for help.
