### ISSUE TITLE
[Enhancement][FLINK-28959][Stream] 504 gateway timeout when consume large number of topics using TopicPatten

### ISSUE THREAD

**Issue by futeng** [streamnative/flink#162]
Our situation is as follows:

- In a single namespace, more than 300 topics(partitioned-topic with a single partition) will report this error;
- Error still exists after resource expansion
- A flick client program consumes 30 to 50 topics per program. This error is bound to be reported after five consecutive programs

Version
- flink-sql-connector-pulsar: 1.15.0.1
- pulsar 2.9.2.17

**Comment by syhily** [comment]
Yep, this is a performance issue. We need extra discussion.

**Comment by syhily** [comment]
Fixed in https://github.com/streamnative/flink/pull/222
