### ISSUE TITLE
[Pulsar Connector] New subscription is expected to have 0 backlog but actually 637.

### ISSUE THREAD

**Issue by imaffe** [streamnative/flink#174]
According to community user, they run into some backlog related issues in 1.15.0.1. 

Setup : 1.15.0.1, default retention policy, StartCursor uses earliest() startcursor, auto ack on.
The user created a my-subscription on day 1 and consumed some messages (). Then users stopped the producer.

On the next day (day 2), user created another source using my-subscription-1, then users observed the following output. The new source is not consuming any data, but has a backlog of 637 (identically to messages consumed on day1). User expect to see a backlog of 0 instead of 637.

Second:
 the mark-delete-position seems points to a ledger from an old subscription instead of the new subscription.

![WechatIMG106.png](https://images.zenhubusercontent.com/61564d60ef4304714f6337a4/facc8f34-9e39-471a-b54a-7a29f6a4e346)

![WechatIMG107.png](https://images.zenhubusercontent.com/61564d60ef4304714f6337a4/67688e8a-4c64-46b8-b6a3-62964f110c36)

**Comment by xyhmnb** [comment]
[issues](https://github.com/streamnative/flink/issues/175)，I guess it's related to this issue

**Comment by syhily** [comment]
This should be resolved by the new poll timeout.
