### ISSUE TITLE
[FLINK-28352][Pulsar Connector] Fix the test failure especially the 

### ISSUE THREAD

**Issue by imaffe** [streamnative/flink#184]
A typical failure includes:  https://github.com/streamnative/flink/runs/7738630757?check_suite_focus=true
https://issues.apache.org/jira/browse/FLINK-28352

**Comment by syhily** [comment]
How about track this issue on #181. An issue can have multiple assignees.

**Comment by syhily** [comment]
Closed for duplicated.
