### ISSUE TITLE
[backport] Backport upcoming PRs to apache/flink back to streamnative/flink

### ISSUE THREAD

**Issue by imaffe** [streamnative/flink#192]

**Comment by syhily** [comment]
Cool! Which PR are you working on now?

**Comment by imaffe** [comment]
I haven't started the backport process yet. @syhily  Just created this issue.

**Comment by imaffe** [comment]
https://github.com/apache/flink/pull/20582

**Comment by imaffe** [comment]
https://github.com/apache/flink/pull/20567

**Comment by imaffe** [comment]
https://github.com/apache/flink/pull/19972

**Comment by imaffe** [comment]
https://github.com/apache/flink/pull/19972

**Comment by syhily** [comment]
First backport for FLINK-27399 https://github.com/streamnative/flink/pull/203

**Comment by syhily** [comment]
Second backport for FLINK-27917 https://github.com/streamnative/flink/pull/204
