### ISSUE TITLE
[FLINK-26161][BUG] PulsarSource: Split should be added to finishedSplit if the the split is empty from beginning.

### ISSUE THREAD

**Issue by imaffe** [streamnative/flink#21]
Currently we  add a split to finishedSplit  in the read for loop, but if the split is empty and never enters for loop it should be checked whether to add to finishedSplit as well. This is an edge case and priority is low.
```
// current
                if (stopCursor.shouldStop(message)) {
                    builder.addFinishedSplit(splitId);
                    break;
                }
```

**Comment by nlu90** [comment]
should handle the case that `StopCursor` is `latest` but the the topic partition is empty

**Comment by imaffe** [comment]
When I look back at this issue, I think I had some misunderstanding at the beginning. If the partitionSplit is empty, it will still enter the for loop. It is empty at the beginning does not mean it will always be empty during the polling.  I'll close this issue.
