### ISSUE TITLE
[BUG] 我用flink消费pulsar数据，当pulsar集群不稳定出现异常之后，会导致flink任务假死。等pulsar集群稳定后，重启flink消费程序，会出现无法消费的情况

### ISSUE THREAD

**Issue by BohanZhang0222** [streamnative/flink#216]
### 问题简述：
我用flink消费pulsar数据，当pulsar集群不稳定出现异常之后，会导致flink任务部分checkpoint失败，等pulsar集群稳定后，重启flink消费程序，会出现无法消费的情况。
另外，StartCursor除了指定latest可以正常消费外。使用fromMessageTime、earliest，都无法正常消费，但是可以在pulsar中看到，subscription是被正确创建出来了的。

### 集群信息：
pulsar版本：2.8.2
flink版本：1.14.4
connector版本：
    source：flink官方1.14.4
    sink：sn-1.14.3.4
订阅模式：Key-shard

### 操作步骤
我对pulsar集群进行了broker扩容，扩容后进行unload操作，但因为新上节点未配置域名解析，导致flink集群无法正确解析pulsar新broker节点的域名，报错unknown host。
我于是配置了域名解析，但是flink的pulsar消费程序并没有死掉，只是卡住了。
我第二天发现了这个问题，于是kill了这个flink程序并进行了重启操作。
重启后，flink程序仍然无法正确消费这个topic的数据。
随后我又进行了一系列操作，比如不从checkpoint恢复，重置了cursor点位到某个ts时间点进行消费，发现仍然无法消费，但是通过pulsar监控发现，subscription的消费点位重置是成功的。
另外我还尝试了在上述操作的基础上修改订阅类型为Exclusive，仍然无法消费。
随后我更换了subscriptionId，尝试重置cursor点位到某个ts时间点进行消费，发现新的subscriptionId在pulsar创建成功，cursor位置正常，但仍无法消费。
最终我再次更换了subscriptionId，尝试使用latest进行消费，消费恢复正常。

### 部分代码
[ProcessX01SignalDataTask.java.zip](https://github.com/streamnative/flink/files/9502458/ProcessX01SignalDataTask.java.zip)

### 部分日志
扩容broker未配置域名解析导致的报错假死日志：
[报错假死.txt](https://github.com/streamnative/flink/files/9502468/default.txt)

重启后无法正常消费的日志：
[重启无法正常消费.txt](https://github.com/streamnative/flink/files/9502602/default.txt)

一些其他尝试中的某次日志（具体不记得了）：
[一些其他尝试.txt](https://github.com/streamnative/flink/files/9502611/default.txt)

**Comment by BohanZhang0222** [comment]
这个问题目前可以稳定的复现。
我又进行了进一步验证，我认为是在producer端导致数据无法写入造成的，因为当我把sink逻辑全部注释掉，采用print的方式，然后采用上述的验证步骤进行操作后，发现数据无论在何种场景下都是可以进行消费并且正常print出来的。
但当我重新启用sink逻辑后，问题就可以重新出现。

**Comment by BohanZhang0222** [comment]
卡住的任务，checkpoint有且一定会有一个失败。
![image](https://user-images.githubusercontent.com/18319597/188810248-30769475-6d62-4199-99a8-7cec1cd61a89.png)

**Comment by BohanZhang0222** [comment]
继续更新一下进展，我开启了debug模式启动了这个flink程序，仍然是其中一个task的日志与其他9个不同，日志也不是一个量级的，其中checkpoint失败的这个task，日志非常多，其他的日志比较少。具体日志如下：
checkpoint失败task的debug日志：
[checkpoint失败task.log.zip](https://github.com/streamnative/flink/files/9524123/checkpoint.task.log.zip)
其他task的debug日志：
[其他task.log.zip](https://github.com/streamnative/flink/files/9524125/task.log.zip)

**Comment by syhily** [comment]
@BohanZhang0222 经过排查，这个问题是因为 Pulsar 存在未被处理的事务所导致的。烦请给 Pulsar 那边提一下 BUG。

**Comment by BohanZhang0222** [comment]
好的，谢谢。
