### ISSUE TITLE
[Enhancement] When Pulsar Source has multiple splits, the splits switch is only triggered when the 10s timeout happen

### ISSUE THREAD

**Issue by imaffe** [streamnative/flink#25]
By default when pulsar source has multiple splits, it will consume from one splits, and when that splits becomes idle more than 10s, it will switch to another splits. This switching mechanism is slow, need to find a way to improve the performance

**Comment by nlu90** [comment]
@syhily could you add more details about the problem?

**Comment by imaffe** [comment]
When I look at the code, I am not sure if the described problem exists.

In my understanding, our code logic is like the following:


1. One PulsarSource can have multiple PulsarSourceReader (based on the parallelism set in Flink), 
2. Every PulsarSourceReader has 1 PulsarFetchManager,  and every PulsarFetchManager can be assigned multiple splits. 
3. In Kafka their FetchManager has only one thread in the executor, but PulsarFetchManager can have multiple threads. 
4. In fact, one thread in the executor (of PulsarFetchManager) corresponds to one SplitFetcher. 
5. Since one SplitFetcher corresponds to one PulsarSplitReader and one PulsarSplitReader corresponds to one Split. It is ok to believe that one thread is responsible for one Split. 

In this case, if one Split becomes idle (no message within 10s), the other threads are still running and other splits are not blocked. 

Maybe I missed something~

**Comment by imaffe** [comment]
In my reproducetion code. the 10 time delay is because the MAX_FETCH_RECORDS is too high, and if the producer produces slowly (1 record per second), then it will not accumulate to 100 records and will wait for the 10s timeout. The trick here is that the "fire" timeout can be decoupled from the message receive timeout. 

The problem is resolved when set  the maxFetchRecords to 1.

**Comment by imaffe** [comment]
This one can be closed and open another issue : include this in the documentation and discuss possible solutions.

**Comment by imaffe** [comment]
Created issue #32
