### ISSUE TITLE
[FLINK-25686][Feature] support schema evolution in source connector

### ISSUE THREAD

**Issue by imaffe** [streamnative/flink#31]
TODO: add more descriptions

**Comment by imaffe** [comment]
Re-assigned to @syhily , and this issue has already been resolved. now we need to backport them which is tracked in #192

**Comment by syhily** [comment]
@imaffe This is not finished yet on official flink side. So I prefer to keep this open.

**Comment by syhily** [comment]
Opps you are right. We should track them on Flink JIRA. So I'll close this issue here.
