### ISSUE TITLE
[FLINK-25740][test] Add pulsar cluster log to stderr if not done so already to get better insights in finding instability 

### ISSUE THREAD

**Issue by imaffe** [streamnative/flink#37]
https://issues.apache.org/jira/browse/FLINK-25740?filter=-1

looks like the pulsar env went down when the setup code is running. Not sure how often this can happen. If the frequency goes high we need to address it.

Another thing we can do to determine the root cause . we need to output the pulsar cluster (in testcontainers) logs to stderr if not done so already

**Comment by syhily** [comment]
I think we can close this issue now.
