### ISSUE TITLE
[SQL Connector] Prefix/Suffix Topic name/pattern configuration support 

### ISSUE THREAD

**Issue by imaffe** [streamnative/flink#62]

**Comment by imaffe** [comment]
We need to discuss whether we need this feature. Flink does not recommend using the table name to identify an external system resource

**Comment by nlu90** [comment]
@imaffe Could you please add the link to Flink doc.

**Comment by imaffe** [comment]
https://streamnative.slack.com/archives/CREAJDFUP/p1652780201525959 Discussion can be found here @nlu90

**Comment by nlu90** [comment]
@imaffe, since this is a publicly available repo, please don't link internal conversation.

I agree that we ask users explicitly specify the complete topic name in the with clause when creating a table.

**Comment by imaffe** [comment]
Closing this issue
