### ISSUE TITLE
[BUG][FLINK-27400] Pulsar connector subscribed the system topic when using the regex

### ISSUE THREAD

**Issue by syhily** [streamnative/flink#84]

**Comment by Technoboy-** [comment]
Currently, the system topic is defined as : the namespace is `pulsar/system`, `heartbeat namespace`, `SLA monitor namespace` or the topic is `__change_events`, `__transaction_buffer_snapshot`, `transaction_coordinator_assign`, `__transaction_log_`, `__transaction_pending_ack`

Please check this method:
https://github.com/apache/pulsar/blob/74747b1c17c77dcd0a71a767307aaf8726c9d925/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java#L2912-L2916

**Comment by syhily** [comment]
https://github.com/apache/flink/pull/19976
